### ISSUE TITLE
[RE0, RE1] Fix black bars in cutscenes

### ISSUE THREAD

**Issue by Keith94** [masterotaku/shader-mods#3]
Unsure if RE0 has black bars, but RE1 definitely does.

**Comment by masterotaku** [comment]
After checking it better, you can already do it. The bloom hotkey (F4) disables the top and bottom black bars, apart from disabling bloom from some objects (not a lot of them). But it disables most of the inventory menu too.

I've made a new version: https://s3.amazonaws.com/masterotaku/Resident+Evil+1/REmake_settings_mod_v1.1.7z

It has a new hotkey, F5, that tries to only disable black bars. It disables some graphics from the inventory menu (a lot less than F4), and the bloom of some elements that are very up or down the screen. It's a bit useless if you only want to use it for cutscenes, because F4 was enough and you don't need the hotkey enabled all the time.

Try it if you want. And remember to rename the d3d9.dll if you use SpecialK.

**Comment by Keith94** [comment]
Cool! I tested the new version in one of the cutscenes near the end of the game, but it appears to be glitched. Maybe you know how to fix that. The bloom and menu downgrades are unfortunate but I suppose I could live with them.

![bhd_2017-11-12_04-19-10](https://user-images.githubusercontent.com/5490615/32698875-e591b314-c760-11e7-864b-de604f44a791.png)

**Comment by masterotaku** [comment]
Go to "Resident Evil Biohazard HD REMASTER\shaderoverride\vertexshaders" and open 4F0EE939.txt.
In line 27, "def c21, 0.999, 0, 0, 0", change that 0.999 for something lower, like 0.900.

It's the value that decides what to draw or not depending on the position in the Y axis. 0.999 worked for the cutscenes I tried without showing bugs, but maybe some cutscenes have bigger black bars that need more tolerance. If 0.900 doesn't work, reduce it even further, at the cost of losing some HUD elements in the pause menu or bloom effects ingame.

I don't know if it's worth the effort compared to the F4 hotkey. First try what I said.

**Comment by Keith94** [comment]
Your suggestion worked. :)

I lowered the value to `837`. Anything higher causes the cutscene glitch above. Might be a good idea to update the fix?

Also, if you don't mind telling me how to change the default state of the effects in the .ini file?
